---
name: "Build APIClient"


on:                          # yamllint disable-line rule:truthy
  schedule:
    - cron: '01 08 * * 6'
  workflow_dispatch:
  push:

env:
  TARGET: GitHubLightAPIClient
  CHANNEL_BASE: GitHubLightAPIClient

jobs:

  "macOS":
    runs-on:
      - self-hosted
      - macOS

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: macOS Build
        working-directory: ./Clients/API
        run: |
          go generate ./...
          $HOME/github/bin/build_go_macos.sh
